#!/usr/bin/env bash
# Vino Manager
# A script to manage Wine prefixes and install/run applications

# Initial checks
commands=("dmenu" "wine" "winetricks")
missing=false

# Check each command
for cmd in "${commands[@]}"; do
	if ! command -v $cmd &>/dev/null; then
		echo "Command not found: $cmd"
		missing=true
	fi
done

# If any command is missing, exit the script
if [ "$missing" = true ]; then
	echo "Please install the missing commands and try again."
	exit 1
fi

# Main variables setup
export WINEPREFIX=""
export WINEARCH=win64
SELECTED_PREFIX=""
BASE_DIR="$HOME/vino"
mkdir -p "$BASE_DIR"
cd "$BASE_DIR"

# Functions
# $1 -- prefix name
create_prefix() {
	mkdir -p "$1"
}

# $1 -- prefix folder name
set_prefix() {
	SELECTED_PREFIX=$1
	WINEPREFIX="$BASE_DIR/$1"
	if [ -z "$(ls -A $WINEPREFIX)" ]; then
		winecfg
	fi
}

# Create Runner script
create_runner() {
	exe=$(program_selection)
	if [[ $exe != "" ]]; then
		cd "$WINEPREFIX"
		cat <<EOF >run.sh
#!/usr/bin/env bash
WINEPREFIX="$WINEPREFIX" wine "$exe"
EOF
		chmod +x run.sh
	fi
}

# Config prefix
config_prefix() {
	while true; do
		selection=$(echo -e "[Cancel]\nWinecfg\nWinetricks\nRun EXE\nCreate Runner" | dmenu -l 5 -p "Config for $SELECTED_PREFIX")
		case "$selection" in
		"Winecfg")
			winecfg
			;;
		"Winetricks")
			winetricks
			;;
		"Run EXE")
			exe=$(program_selection)
			if [[ $exe != "" ]]; then
				wine "$exe"
			fi
			;;
		"Create Runner")
			create_runner
			break
			;;
		*)
			break
			;;
		esac
	done
}

# $1 -- prefix folder to delete
delete_prefix() {
	sure=$(echo -e "No\nYes" | dmenu -p "Delete $1?")
	if [[ $sure = "Yes" ]]; then
		rm -r "$BASE_DIR/$1"
		main
	else
		main
	fi
}

program_selection() {
	cd "$BASE_DIR"
	current=""
	while true; do
		list=$(ls)
		current=$(echo -e "[Cancel]\n..\n$list" | dmenu -i -l 20 -p "select .exe")
		if [[ $current == ".." ]]; then
			cd ..
		elif [[ $current == *.exe || $current == *.msi ]]; then
			echo "$(pwd)/$current"
			break
		elif [[ $current == "[Cancel]" ]]; then
			break
		else
			cd "$current"
		fi
	done
}

main() {
	selection=$(echo -e "[Cancel]\nLaunch app\nConfig a prefix\nCreate a prefix\nDelete a prefix" | dmenu -l 5 -p "What do you want to do?")
	case "$selection" in
	"Launch app")
		cd "$BASE_DIR"
		prefix=$(ls | dmenu -l 10 -p "Select a prefix")
		set_prefix $prefix
		bash "$WINEPREFIX/run.sh"
		;;
	"Config a prefix")
		cd "$BASE_DIR"
		set_prefix $(ls | dmenu -l 10 -p "Select a prefix")
		config_prefix
		main
		;;
	"Create a prefix")
		cd "$BASE_DIR"
		name=$(echo "" | dmenu -p "Type a name for the prefix")
		create_prefix $name
		set_prefix $name
		config_prefix
		;;
	"Delete a prefix")
		cd "$BASE_DIR"
		delete_prefix $(ls | dmenu -l 10 -p "Prefix to delete")
		;;
	*)
		exit 0
		;;
	esac
}

main
